
#-----------------------------------------------
#Config that does not have impact on performance
#-----------------------------------------------


random_seed: 0b011011

#-----------------------------------------------
#1. Dataset
#-----------------------------------------------

dataset:
  iscodec: True
# #directory that have every dataset in it.
#   data_dir: "/home/woongjib/Projects/SSLBWE/sr/"
#   nb_train: "recon_mpeg/MP3_sr16_train_16kbps/train"
#   nb_val: "recon_mpeg/MP3_sr16_train_16kbps/test"
#   wb_train: "VCTK/16Khz/train"
#   wb_val: "VCTK/16Khz/test"

#So for this case, wideband test dataset should be located at "/media/zeroone/target/test"


  batch_size: 16
  seg_len: 3.6
  ## Segment audio length
  
  num_workers: 32
 
#-----------------------------------------------
#2. Model
#-----------------------------------------------

model:
  generator: SEANet_TFiLM
  # hubert, w2v, wavlm
  ms_mel_loss_config:
            n_fft_list: [32, 64, 128, 256, 512, 1024, 2048]
            hop_ratio: 0.25
            mel_bin_list: [5, 10, 20, 40, 80, 160, 320]
            reduction: mean
            loss_ratio: 1.0
            sr: 16000
  kmeans_path: '/home/woongjib/Projects/BESSL_AudioMAE/kmeans/K64_MAE.pkl'
 
  discriminator: MBSTFTD
  MultiBandSTFTDiscriminator_config:
      C: 32
      n_fft_list: [2048, 1024, 512]
      hop_len_list: [512, 256, 128]
      band_split_ratio:
          - [0.0, 0.1]
          - [0.1, 0.25]
          - [0.25, 0.5]
          - [0.5, 0.75]
          - [0.75, 1.0]

#-----------------------------------------------
#3. Loss
#-----------------------------------------------


#No information

#-----------------------------------------------
#4. Optimizer (ADAM)
#-----------------------------------------------

optim:
  learning_rate: 0.0001
  
  B1: 0.5
  B2: 0.9


#-----------------------------------------------
#Training
#-----------------------------------------------

train:
  epoch_save_start: 1
  val_epoch: 5
  
  ckpt_save_dir: "./ckpt_tfilm_K64"
#Path of output of validation. 
  output_dir_path: "./output_wavlm"
  logger_path: "./logger_wavlm"

  max_epochs: 200

  devices:
    - 0
    #- 1
    # -2 ... if you are using DDP

  # True if load from previous
  ckpt: False
  ckpt_path: "/mnt/hdd/weights/kmeans/kmeans_modelweight_64n_wavlm.pkl"



